### ISSUE TITLE
Question about configuration files

### ISSUE THREAD

**Issue by sveyret** [thiagodp/concordialang#52]
I've just release [confinode](https://www.npmjs.com/package/confinode) which is a library for managing configuration file in various formats. I saw this project and wondered if it is possible to create a configuration file using _concordialang_ and if it would be pertinent to support it in _confinode_.

**Comment by thiagodp** [comment]
Hello @sveyret, thanks for getting in touch. It looks like `confinode` offers some interesting options.

Currently, this project uses [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) to deal with configuration loading (see [OptionsHandler](https://github.com/thiagodp/concordialang/blob/master/modules/app/OptionsHandler.ts)).

The parameter `--init` makes the Concordia Compiler to create a JSON configuration file named `.concordiarc`. There is a plenty of configurable [options](https://github.com/thiagodp/concordialang/blob/master/modules/app/Options.ts). The most common ones are `directory`, `language`, `plugin`, `dirScript`, and `dirResult`.

Is the idea of Confinode to load multiple configuration files with a single interface? In that case, is it correct to say that adding support to Concordia means to create a proper loader for it?

**Comment by sveyret** [comment]
I know about _cosmiconfig_ which I found great, but I decided to create _confinode_ because of a philosophical difference with the author of _cosmiconfig_. Because we always find that our children are great, I think that _confinode_ is far more powerful than _cosmiconfig_… :wink: 

Basically, what I mean by supporting _Concordia_ is, as you said, creating a loader for it. To my understanding _Concordia_ is a kind of a language. Therefore, I though that it may be possible to write configuration files in _Concordia_, which would especially be interesting for people using this language. But maybe I am mistaken?

**Comment by thiagodp** [comment]
Concordia can be used to describe software requirements in a restricted natural language. It includes things like Features and Scenarios and details their expected behavior using Variants (a kind of test case for user interfaces). The compiler "understands" these declarations (using natural language processing and other techniques) to generate test cases with data and oracles. These test cases are converted to test scripts using some plug-in defined by the user - such as the plugin for CodeceptJS + WebDriverIO.

Thus, Concordia is not aimed to write configuration files.

**Comment by sveyret** [comment]
OK, thank you…
